apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-version
  name: app-v1
spec:
  replicas: 8
  selector:
    matchLabels:
      app: app-version
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-version
    spec:
      containers:
      - image: docker.io/httpd
        name: httpd
